source("renv/activate.R")
options(blogdown.generator.server = TRUE)
options(blogdown.ext = '.Rmd', blogdown.author = 'ravic')
options(blogdown.new_bundle = FALSE)
options(blogdown.knit.on_save = FALSE) 
