baseurl = "https://ravic.netlify.com/"
title = "ravic_"
author = "Ravi Chandrasekaran"
copyright = "Copyright (c) 2020 Ravi Chandrasekaran"
canonifyurls = true
paginate = 3
theme = "hugo-finite"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
math = true

# Date format (refer to Go's date format: http://flippinggodateformat.com)
# Examples: "Mon, Jan 2, 2006" or "2006-01-02"
#date_format = "2 January 2006"

# Publications can have a Params.publication for citation references.
# Publications can have a Params.kind, such as "book".
# Both parameters are mapped to an icon in partials/pub-icon.html.

bio_full = "Ravi Chandrasekaran!"
bio_twitter = "ravic_"

# Title of posts section on main page.
#posts_title = "Posts"

# Number of posts to show on main page.
#posts_count = 2

# Title of publications section on main page.
#pubs_title = "Publications"

# Number of publications to show on main page.
#pubs_count = 5

# [[params.education]]
#  course = "Bachelor in Civil Law"
#  institution = "University of Orléans"
#  year = 1626

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:ravichandrasekaran@gmail.com"
  text = "ravichandrasekaran@gmail.com"
    
[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "https://twitter.com/ravic_"
  text = "@ravic_"
  site = "Twitter"

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "https://github.com/ravichandrasekaran"
  text = "Ravi Chandrasekaran"
  site = "GitHub"


# Navigation Links
# The weight parameter defines the order that the links will appear in.

# [[menu.main]]
#  name = "Publications"
#  url = "/publication/"
#  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 2

[[menu.main]]
  name = "Contact"
  url = "/#contact"
  weight = 3
